apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ubuntu-tool
  namespace: lab
  labels:
    os: ubuntu
    app: salon
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
      app: salon 
  template:
    metadata:
      name: ubuntu-tool
      namespace: lab
      labels:
        os: ubuntu
        app: salon 
    spec:
      containers:
      - image: ubuntu
        name: ubuntu-os
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-c"
        - |
          rm /etc/apt/sources.list
          cat > /etc/apt/sources.list <<EOF
          deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
          deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
          deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
          deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
          deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
          deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
          EOF
          while true;do echo hello;sleep 1;done
      restartPolicy: Always